baseURL: "faye-romero.github.io" 
title: Faye Romero
theme: PaperMod

#test

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: SciComm
          url: scicomm/
          weight: 4
        - name: Media
          url: media/
          weight: 5 
        - name: Publications
          url: publications/
          weight: 2
        - name: Research
          url: research/
          weight: 1
        - name: Updates
          url: updates/
          weight: 6 
        - name: Notebook
          url: notebook/
          weight: 3 
#        - name: Blog
#          url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
#          weight: 6

params:
    description: "This website hosts Faye Romero's research and career information."
    author: Faye Romero
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["scicomm","courses","publications","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Faye Romero
          subtitle: "I am a Biology PhD candidate and NSF Graduate Research Fellow at the University of Rochester advised by <u>[Dr. Nancy Chen](https://popgenchenlab.github.io)</u>. My current research focuses on exploring the evolutionary and conservation genetics of small populations using the threatened <u>[Florida Scrub-Jay](https://www.archbold-station.org/projects/long-term-florida-scrub-jay-project/)</u> as a model system."
          imageUrl: "Romero,Faye.png"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Research
              url: research/
            - name: Publications
              url: publications/
            - name: Notebook
              url: notebook/
            - name: SciComm
              url: scicomm/
            - name: Media
              url: media/
            - name: Updates
              url: updates/
#            - name: Tags
#              url: tags/
#            - name: Archive
#              url: archive/
#            - name: Blog
#              url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)

    socialIcons:
        - name: CV
          url: FayeRomero_CV_Oct2025.pdf
        - name: Email
          url: location/
        - name: Location
          url: location/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=hDpEi8YAAAAJ&hl=en
        - name: GitHub
          url: https://github.com/faye-romero
        - name: Bluesky
          url: https://bsky.app/profile/fayeromero.bsky.social

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Faye Romero"
      icon: dna-icon.png
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2